# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: mkdir ivy
    - working-directory: ivy
      run: |
        git clone https://git-wip-us.apache.org/repos/asf/ant-ivy.git
    - working-directory: ivy/ant-ivy
      run: |
        ant jar
        ls build/artifact
        sudo mv build/artifact/org.apache.ivy_2.6.0.alpha_20210613224137.jar ~/.ant/lib/ivy.jar
    - run: sudo apt-get install ivy
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
